myproject/blog/urls.py
from django.urls import path
from .views import index, blog_detail

app_name = 'blog'  # Ensure app_name is set

urlpatterns = [
    path('', index, name='blog_list'),
    path('<slug:slug>/', blog_detail, name='blog_detail'),
]

myproject/bookings/urls.py
from django.urls import path
from . import views

app_name = 'bookings'

urlpatterns = [
    path('book/', views.booking_view, name='book_slot'),
    path('submit_to_web3forms/<int:booking_id>/', views.submit_to_web3forms, name='submit_to_web3forms'),
    path('success/', views.booking_success_view, name='booking_success'),
]

myproject/home/urls.py
from django.urls import path
from .views import index, facebook_page

app_name = 'home'

urlpatterns = [
    path('', index, name='index'),
    path('facebook-page/', facebook_page, name='facebook_page'),  # New URL pattern for the Facebook page
]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import handler500 , handler404, handler403, handler400
from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static
from . import views






handler500 = views.handler500
handler404 = views.handler404
handler403 = views.handler403
handler400 = views.handler400
urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('', include('home.urls', namespace='home')),
    path('about/', include('about.urls', namespace='about')),
    path('gallery/', include('project_gallery.urls', namespace='gallery')),
    path('services/', include('packages_services.urls', namespace='services')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('bookings/', include('bookings.urls', namespace='bookings')),
    path('store/', include('developer_store.urls', namespace='developer_store')),
] 
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += [
    path('sitemap.xml', serve, {
        'path': 'sitemap.xml',
        'document_root': settings.STATIC_ROOT,
    }),
]

myproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
 

    <meta name="robots" content="index, follow">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="language" content="English">
    <meta name="author" content="CleanDesignUK">
  
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
   
    <link rel="icon" type="image/webp" href="https://res.cloudinary.com/dz18uvfpa/image/upload/v1716203082/tge3nz3lwlahqfg163md.webp" alt="CleanDesignUK Logo">
    <link  href="{% static 'css/style.css' %}" rel="stylesheet" >
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=AW-16513767694"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'AW-16513767694');
</script>
    
    



        {% block extra_css %} <!-- Placeholder for additional page-specific CSS -->
        {% endblock %}
{% block extra_head %}
{% endblock %}
</head>
<body class="d-flex flex-column min-vh-100">
   
    <nav class="navbar fixed-top navbar-expand-lg">
        <div class="container-fluid">
            <a class="navbar-brand m-lg-2 d-flex justify-content-evenly align-items-center" href="{% url 'home:index' %}">
                <img src="https://res.cloudinary.com/dz18uvfpa/image/upload/v1716203082/tge3nz3lwlahqfg163md.webp" class="border border-danger rounded" alt="CleanDesignUK Logo" style="height: 50px;">
                <span class="text-size-brand">CleanDesignUK</span> 
            </a>
            <button class="navbar-toggler mr-md-2" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon">
                    <i class="fas fa-bars icon-sizing"></i>
                </span>
            </button>
            <div class="collapse navbar-collapse w-100 d-lg-flex justify-content-around align-items-center m-2" id="navbarNav" style="max-width: 1400px;">
                <ul class="navbar-nav d-lg-flex justify-content-around align-items-center">
                    <li class="nav-item mx-auto">
                        <a class="nav-link px-lg-3 px-xl-4 {% if request.resolver_match.url_name == 'home:index' %}active{% endif %}" href="{% url 'home:index' %}">Home</a>
                    </li>
                    <li class="nav-item mx-auto">
                        <a class="nav-link px-lg-3 px-xl-4 {% if request.resolver_match.url_name == 'blog_list' %}active{% endif %}" href="{% url 'blog:blog_list' %}">Blog</a>
                    </li>
                    <li class="nav-item mx-auto">
                        <a class="nav-link px-lg-3 px-xl-4 {% if request.resolver_match.url_name == 'about' %}active{% endif %}" href="{% url 'about:index' %}">About Us</a>
                    </li>
                    <li class="nav-item mx-auto">
                        <a class="nav-link px-lg-3 px-xl-4 {% if request.resolver_match.url_name == 'gallery' %}active{% endif %}" href="{% url 'gallery:index' %}"> Gallery</a>
                    </li>
                    <li class="nav-item mx-auto">
                        <a class="nav-link px-lg-3 px-xl-4 {% if request.resolver_match.url_name == 'services' %}active{% endif %}" href="{% url 'services:index' %}"> Services</a>
                    </li>
                    <li class="nav-item mx-auto">
                        <a class="nav-link px-lg-3 px-xl-4 {% if request.resolver_match.url_name == 'contact' %}active{% endif %}" href="{% url 'contact:index' %}">Contact</a>
                    </li>
                    <!-- Added Store Link -->
                    <li class="nav-item mx-auto">
                        <a class="nav-link px-lg-3 px-xl-5 {% if request.resolver_match.url_name == 'store:index' %}active{% endif %}" href="{% url 'developer_store:index' %}">Developer Store </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

<main class=" flex-shrink-0 mt-5 pt-3 pt-lg-5">

    <div class="modal fade" id="privacyPolicyModal" tabindex="-1" aria-labelledby="privacyPolicyModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-scrollable">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="privacyPolicyModalLabel">Privacy Policy</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <h6>Data Collection and Use</h6>
                    <p>We collect the following data: first name, surname, and email address when you fill out our contact form. This information is held for up to 3 days to respond to your query.</p>
                    <h6>Cookies and Third Party Services</h6>
                    <p>We use third-party cookies from Cloudinary to enhance image load times on return visits to our website. These cookies are used solely for performance improvements.</p>
                    <h6>Your Rights</h6>
                    <p>Under the GDPR, you have the right to access, correct, transfer, and delete your personal data. You also have the right to object to certain processing and restrict certain processing activities.</p>
                    <p>If you wish to exercise any of these rights, please contact us at our provided contact details.</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

    <!-- Cookie Consent Modal -->
<div class="modal fade" id="cookieConsentModal" tabindex="-1" aria-labelledby="cookieConsentModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="cookieConsentModalLabel">Cookie Policy</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>We use cookies, including third-party cookies from Cloudinary for faster image load times on repeat visits. By continuing to browse our site, you agree to our use of cookies.</p>
                <p>To learn more about how we use cookies and how you can manage them, read our <a href="#" data-bs-toggle="modal" data-bs-target="#privacyPolicyModal" data-bs-dismiss="modal">Privacy Policy</a>.</p>
                <p>You can disable cookies by adjusting your browser settings.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Accept Cookies</button>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="cookiePolicyModal" tabindex="-1" aria-labelledby="cookiePolicyModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="cookiePolicyModalLabel">Cookie Policy</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>We use third-party cookies from Cloudinary to enhance image load times on return visits to our website. These cookies are used solely for performance improvements.</p>
                <p>By continuing to use our site, you accept our use of cookies. You can disable cookies by adjusting the settings in your browser.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<div class="booking-icon p-1">
    <a href="{% url 'bookings:book_slot' %}" title="Book Your Free Website Consultation">
        <i class="fas fa-calendar-check "></i> <!-- Font Awesome calendar-check icon -->
    </a>
</div>
{% block content %}
{% endblock %}
</main>

<footer class="">
    <div class=" text-center text-md-left py-3">
        <div class="row custom-footer">
            <div class="col-12 col-lg-3 mt-md-0 mt-3">
                <h5 class="text-uppercase">CleanDesignUK</h5>
                <p>Bringing you the best in web design and development.</p>
            </div>
            
            <div class="col-md-8 col-lg-6 mb-md-0 mb-3">
                <h5 class="text-uppercase">Follow Us</h5>
                <ul class="list-unstyled d-flex justify-content-between align-items-center row">
                    <li class="col-6 col-md-4">
                        <a href="{% url 'home:facebook_page' %}" class="footer-link " target="_blank"><i class="fab fa-facebook"></i> Facebook</a>
                    </li>
                    <li class=" col-6 col-md-4">
                        <a href="https://www.youtube.com/@CleanDesignUK" class=" footer-link " target="_blank"><i class="fab fa-youtube"></i> YouTube</a>
                    </li>
                    <li class=" col-6 col-md-4">
                        <a href="http://linkedin.com/in/jesseross001" class=" footer-link " target="_blank"><i class="fab fa-linkedin"></i> LinkedIn</a>
                    </li>
                    <li class=" col-6 col-md-4">
                        <a href="https://www.instagram.com/cleandesign_uk" class=" footer-link" target="_blank" ><i class="fab fa-instagram"></i> Instagram</a>
                    </li>
                    <li class=" col-6 col-md-4">
                        <a href="https://maps.app.goo.gl/T6VnJcv8yhLTeay86" class=" footer-link " target="_blank"><i class="fab fa-google"></i> Business</a>
                    </li>
                    <li class=" col-6 col-md-4">
                        <a href="mailto:cleandesign.uk@gmail.com" class=" footer-link " target="_blank"><i class="fas fa-envelope"></i> Email Us</a>
                    </li>
                </ul>
            </div>
            <div class="col-md-4 col-lg-2 mb-md-0 mb-3">
                <h5 class="text-uppercase">Policies</h5>
                <ul class="list-unstyled row ">
                    <li class="col-6 col-md-12">
                        <a href="#" class="policy-footer-size" data-bs-toggle="modal" data-bs-target="#privacyPolicyModal">Privacy Policy</a>
                    </li>
                    <li class="col-6 col-md-12 ">
                        <a href="#!" class="policy-footer-size" data-bs-toggle="modal" data-bs-target="#cookiePolicyModal">Cookie Policy</a>

                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>
<!-- Bootstrap JS and dependencies -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://kit.fontawesome.com/11665d5c0d.js" crossorigin="anonymous"></script>
<script src="{% static 'js/base.js' %}"></script> <!-- Load the external JavaScript file -->
</body>
</html>